"""add phone number

Revision ID: 635d95e56430
Revises: 
Create Date: 2022-09-14 22:29:54.741958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d95e56430'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
